### ISSUE TITLE
² $ initialise le viewport 2 fois

### ISSUE THREAD

**Issue by AssociationSirius** [AssociationSirius/requiem#1]
² $ exécute visiblement 2 fois la réinitialisation du disque, ainsi que le chargement du landscape.

**Comment by lionelruiz13** [comment]
Ceci est changé avec le nouveau initial.sts que je ne vous ai pas encore passé.
Il y a aussi des modifications avec le clear_mess.sts
Je commite tout ça dès que j'y arrive et cela devrait être bon.
