### ISSUE TITLE
text display ?

### ISSUE THREAD

**Issue by AssociationSirius** [AssociationSirius/requiem#5]
il m'est facile de faire un accesseur rapide à un texte pour modifier un texte en particulier 

genre:

texte name XXX transition duration 2

utile ou pas ?

**Comment by PierreSirius** [comment]
Pour la transition d'une certaine durée. oui , c'est top !

**Comment by lionelruiz13** [comment]
1) le nombre de termes ne convient pas.
2) en général on veut pas en changer si souvent que ça.
le set est suffisant et fait le même travail.
Il faudrait avoir besoin de textes EN MÊME TEMPS qui aient un temps de fondu différent.
Perso, je n'en vois pas l'intérêt et ça compliquerait le language inutilement.

**Comment by AssociationSirius** [comment]
sujet clôt.

**Comment by PierreSirius** [comment]
Les textes en même temps! Oui !
Je pensais a des durées différentes, car je pense aux utilisateurs qui sont tous différents. Je pense qu'il faudrait cette fonction avec un fade défini mais qui est modulable si on le désire.
J'exprime ce que j'ai en tête, mais je ne suis pas informaticien donc je ne pense pas au codage qui se cache derrière...

**Comment by lionelruiz13** [comment]
Salut Pierre (et olivier). Tu veux dire que tu aurais besoin que des textes apparaissant en même temps (ou presque) mais avec des durée d'apparition différentes ? Idem pour la disparition. ça ferait un pue bizarre. Qu'on change la variable de durée de fondu à la volée pour changer de mode, c'est logique. Programmer une  durée différente pour chaque texte, je n'en aurai jamais besoin et je ne vois pas d'exemple où ça servirait sauf pour une démo psychédélique. Mais pour les sous-titrages et les infos on screen et même les crédits, ce genre de travail est désuet.

**Comment by PierreSirius** [comment]
oui et non ... je ne veux pas faire un spectacle de discothèque avec apparition en différentes couleur et à différents endroits des textes..  Quoi que..  ;)
Ce que je veux dire... oui,  je voudrai lorsqu'un texte apparait, faire disparaitre l'autre. Je voudrai aussi faire apparaitre plusieurs textes à différents endroits du dôme.. Comme lorsque les étoiles apparaissent au coucher de soleil, on pourrait imaginer que du texte apparaisse aussi.. 
Ensuite, pour cette variable durée, je sous entendais que moi , par exemple, je veux un fade de 2 s, mais toi tu veux peut être 3 s et Olivier que 1 s. Chaque utilisateur est différent. Donc on pourrait mettre une valeur par défaut, et si on veut la changer , avoir cette possibilité.. Messieurs les informaticiens,  est-ce possible? Si trop de contraintes pour  , vous laissez tomber.. Mais la question étant posée, je done mon avis d'utilisateur et j'essaie de penser aux autres utilisateurs.

**Comment by lionelruiz13** [comment]
C'est déjà possible et mieux que tu penses.
Car tu peux en changer à loisir pendant un script, la valeur de fondu.
Juste que quand tu fais apparaitre 7 textes en même temps ce sera avec la même durée. Celle que tu veux mais la même. 
Donc on est d'accord.
Ce que proposait Olivier c'était que les 7 textes apparaissent en même temps (ou presque) mais avec des durées différentes.

**Comment by PierreSirius** [comment]
ok, je vais noter dans un coin que je dois faire un script test montrant ttes ces fonctionnalités... je pense que cela mérite une démo.
