### ISSUE TITLE
text display minuté ?

### ISSUE THREAD

**Issue by AssociationSirius** [AssociationSirius/requiem#6]
que penses tu de cette commande ?

text name XXX display on** duration 15**

ou duration 15 affiche le texte sur le dôme pendant 15s ?

**Comment by PierreSirius** [comment]
Perso , je ne vois pas trop l'utilité, car lors d'un ecript, je parle et je commente et pas tjs à la même vitesses..
Par contre cette fonction pour des scripts auto, est super, je pense.. donc oui , à faire !

**Comment by lionelruiz13** [comment]
Désolé de te contredir encore une fois Pierre, mais cette commande est trop dangereuse.
Soit ça foire hors d'un script car il faudrait faire un timer exprès qui tourne en tâche de fond, sinon c'est caduque. Et en plus à lire séquentiellement ça perturbe. Alors que définir un fade in et un fade out lors du drop est mieux tout en tenant compte du set text_fading_duration.

**Comment by PierreSirius** [comment]
je m'incline.... vite peut être mais je m'incline....
Sans rire, Lionel, j'ai bien compris ton argumentation.

**Comment by AssociationSirius** [comment]
Fausse bonne idée, je clos.
